language: node_js
node_js:
- lts/*

before_install:
- npm install -g @angular/cli
install: npm install

branches:
  only:
  - master


deploy:
  provider: heroku
  app: my-own-steam-app
  api_key:
    secure: "c6c0a8eb-e7fc-4acb-aff8-a44dbe12350c"