language: node_js
node_js:
- '16.14.0.'

before_install:
- npm install -g @angular/cli
install: npm install

branches:
  only:
  - main

script: "true"

deploy:
  provider: heroku
  app: 
    master: my-own-steam-app
  api_key:
    secure: "b1b1d581-8d72-4f30-bb05-a6044d5feb33"
  strategy: git
  edge: true
  on:
    all_branches: true




