language: node_js
node_js:
- '16.14.0.'

before_install:
- npm install -g @angular/cli
install: npm install

branches:
  only:
  - main

script: 'true'

deploy:
  provider: heroku
  app: 
    master: my-own-steam-app
  api_key:
    secure: "c6c0a8eb-e7fc-4acb-aff8-a44dbe12350c"
  strategy: git
  edge: true
  on:
    branch: master




